"""Create a reproducible local RTX 4050 demo proof pack.

This utility does not generate video. Run it on the same machine that generated
the clips to capture hardware evidence, diagnostics, and SHA-256 hashes.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

EXPECTED_WORKFLOWS = (
    "text-to-video",
    "image-to-video",
    "action",
    "cartoon-continuity",
)


def _run(command: list[str]) -> tuple[int, str]:
    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = (result.stdout or "") + (result.stderr or "")
        return result.returncode, output.strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return 1, str(exc)


def detect_nvidia_gpu() -> dict[str, str]:
    exe = shutil.which("nvidia-smi")
    if not exe:
        return {"available": "false", "name": "", "driver": "", "memory_mb": "", "raw": "nvidia-smi not found"}

    query = [
        exe,
        "--query-gpu=name,driver_version,memory.total",
        "--format=csv,noheader,nounits",
    ]
    code, output = _run(query)
    if code != 0 or not output:
        return {"available": "false", "name": "", "driver": "", "memory_mb": "", "raw": output}

    first = output.splitlines()[0]
    parts = [part.strip() for part in first.split(",")]
    while len(parts) < 3:
        parts.append("")
    return {
        "available": "true",
        "name": parts[0],
        "driver": parts[1],
        "memory_mb": parts[2],
        "raw": output,
    }


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_commit(repo_root: Path) -> str:
    code, output = _run(["git", "-C", str(repo_root), "rev-parse", "HEAD"])
    return output.splitlines()[0] if code == 0 and output else "unknown"


def diagnostics(repo_root: Path) -> str:
    code, output = _run([sys.executable, str(repo_root / "run.py"), "--check"])
    return f"exit_code={code}\n{output}".strip()


def build_manifest(
    repo_root: Path,
    clips: list[Path],
    gpu: dict[str, str],
    *,
    allow_non_4050: bool = False,
) -> dict:
    gpu_name = gpu.get("name", "")
    is_4050 = "RTX 4050" in gpu_name.upper()
    if not allow_non_4050 and not is_4050:
        raise RuntimeError(
            f"RTX 4050 not detected (detected: {gpu_name or 'none'}). "
            "Run this proof capture on the actual RTX 4050 machine that rendered the demo."
        )

    clip_rows = []
    for path in clips:
        resolved = path.expanduser().resolve()
        if not resolved.is_file():
            raise FileNotFoundError(resolved)
        clip_rows.append(
            {
                "file": str(resolved),
                "bytes": resolved.stat().st_size,
                "sha256": sha256_file(resolved),
            }
        )

    return {
        "schema": 1,
        "captured_at_utc": datetime.now(timezone.utc).isoformat(),
        "repository": "logeshv586-code/Ltxvideo",
        "git_commit": git_commit(repo_root),
        "hardware": {
            "gpu": gpu_name,
            "driver": gpu.get("driver", ""),
            "vram_mb": gpu.get("memory_mb", ""),
            "python": platform.python_version(),
            "os": platform.platform(),
        },
        "required_workflows": list(EXPECTED_WORKFLOWS),
        "clips": clip_rows,
        "shots": [
            {
                "workflow": workflow,
                "prompt": "",
                "reference_image": "",
                "resolution": "384x224",
                "frames": 49,
                "fps": 30,
                "seed": "",
                "steps": "",
                "guidance": "",
                "generation_seconds": "",
                "output": "",
            }
            for workflow in EXPECTED_WORKFLOWS
        ],
        "claim_notes": [
            "All listed clips must have been generated by this repository on the captured RTX 4050 system.",
            "720p/1080p delivery exports are resizes unless native diffusion resolution is explicitly documented.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        default="docs/demo/proof",
        help="Directory for proof.json, diagnostics.txt, and nvidia-smi.txt",
    )
    parser.add_argument(
        "--clip",
        action="append",
        default=[],
        help="Path to a locally generated demo clip. Repeat for multiple clips.",
    )
    parser.add_argument(
        "--repo-root",
        default=str(Path(__file__).resolve().parents[1]),
        help="Repository root; defaults to the parent of tools/.",
    )
    parser.add_argument(
        "--allow-non-4050",
        action="store_true",
        help="Testing only. Never use this flag for published RTX 4050 proof.",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    output_arg = Path(args.output_dir)
    output_dir = (repo_root / output_arg).resolve() if not output_arg.is_absolute() else output_arg.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    gpu = detect_nvidia_gpu()
    try:
        manifest = build_manifest(
            repo_root,
            [Path(item) for item in args.clip],
            gpu,
            allow_non_4050=args.allow_non_4050,
        )
    except (RuntimeError, FileNotFoundError) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 2

    (output_dir / "nvidia-smi.txt").write_text(gpu.get("raw", ""), encoding="utf-8")
    (output_dir / "diagnostics.txt").write_text(diagnostics(repo_root) + "\n", encoding="utf-8")
    (output_dir / "proof.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"[PASS] Wrote proof pack to {output_dir}")
    print("Fill in the four shot records in proof.json after generation, then publish the demo and proof together.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
